name: Create and publish a package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Setup .npmrc auth
      run: |
        echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}\n@banou26:registry=https://npm.pkg.github.com" > .npmrc
        npm ci --ignore-scripts

    - run: npm ci

    - run: npm run build

    - name: Upload dist folder artifacts
      uses: actions/upload-artifact@v2
      with:
          name: dist
          path: "dist/*"

  release:
    name: "Release"
    needs: [build]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Banou26'
    steps:
    - name: Download dist folder artifacts
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: ./dist
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: "@Banou26"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/manifest.json
          dist/package.asar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
